name: dynamic_widget_plus
description: A Backend-Driven UI toolkit, build your dynamic UI with json, and the json format is very similar with flutter widget code。
version: 1.0.0
homepage: https://github.com/hardik6005/dynamic_widget_plus.git

environment:
  sdk: '>=2.18.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  logging: ^1.2.0
  http: ^1.1.0
  font_awesome_flutter: ^10.5.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
